<Window
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:MTool_V1"
        xmlns:Source="clr-namespace:MTool_V1.Tools_main_Resources"
        xmlns:Stlyes="clr-namespace:MTool_V1.Styles"
        xmlns:Forms="clr-namespace:System.Windows.Forms;assembly=System.Windows.Forms"
        xmlns:syncfusion="http://schemas.syncfusion.com/wpf" xmlns:Forms1="clr-namespace:Spire.Spreadsheet.Forms;assembly=Spire.Spreadsheet"
        xmlns:PropertyEditing="clr-namespace:System.Activities.Presentation.PropertyEditing;assembly=System.Activities.Presentation" xmlns:PointCloudManager="clr-namespace:Autodesk.AutoCAD.ViewModel.PointCloudManager;assembly=AcWindows" xmlns:ComponentModel="clr-namespace:System.ComponentModel;assembly=System" 
        x:Class="MTool_V1.Main_Window_MTools"
        mc:Ignorable="d"
        Background="Transparent"
        d:DesignHeight="450" 
        d:DesignWidth="600"
        x:Name="MToolsMain"
        Title="MTools" 
        ResizeMode="CanResizeWithGrip"
        MinWidth= "600" 
        MinHeight="600"
        Margin="0" 
        Opacity="0.9" Foreground="{x:Null}"  
        ScrollViewer.VerticalScrollBarVisibility="Disabled" 
        AllowDrop="True" Tag="MTools" 
        WindowStyle="None" VerticalAlignment="Center" 
        HorizontalContentAlignment="Center" VerticalContentAlignment="Center"
        UseLayoutRounding="True" HorizontalAlignment="Center" IsTabStop="False" Focusable="False" MouseDown="mousedown" SizeToContent="Width" WindowStartupLocation="CenterScreen" ToolTip="MTools">

    <Window.Resources>
        <Stlyes:Styles/>
    </Window.Resources>

    <Window.Effect>
        <DropShadowEffect/>
    </Window.Effect>
    <Border  Style="{StaticResource Border_MAin}" CornerRadius="10,10,0,0">
        <Grid x:Name="MainW" >
            <Grid.ColumnDefinitions >
                <ColumnDefinition Width="220"/>
                <ColumnDefinition Width="380"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition 
                                   MinHeight="10"
                                   MaxHeight="10"/>
                <RowDefinition Height="70*"
                                   MinHeight="70"
                                   MaxHeight="70"/>
                <RowDefinition  Height="203*"
                                    MinHeight="350"/>
                <RowDefinition 
                                   MinHeight="20"
                                   MaxHeight="20"/>
            </Grid.RowDefinitions>
            <Border x:Name="TopWinMove"
                    Grid.Column="0"
                    Grid.Row="0"
                        Grid.RowSpan="2" CornerRadius="10,10,10,10"
                       />
            <Border x:Name="Hedder_Panel"
                        Grid.Row="0"
                        Grid.ColumnSpan="2"
                        Grid.RowSpan="2"
                        BorderThickness="0"
                        CornerRadius="10,10,0,0" 
                        ScrollViewer.VerticalScrollBarVisibility="Disabled" 
                        Grid.IsSharedSizeScope="True" 
                        UseLayoutRounding="True"
                        Focusable="True">
                <Border.Background>
                    <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0" SpreadMethod="Pad" MappingMode="RelativeToBoundingBox">
                        <GradientStop Color="#FF1E1D25" Offset="0.985"/>
                        <GradientStop Color="#FF211F2D" Offset="0.913"/>
                        <GradientStop Color="#FF403D50"/>
                        <GradientStop Color="#FF28243D" Offset="0.892"/>
                    </LinearGradientBrush>
                </Border.Background>
            </Border>

            <TextBlock x:Name="Info_Hedder"
                    Grid.Column="1"
                       Grid.Row="1"
                       Margin="10,0,0,10"
                       TextBlock.FontSize="11"
                       Foreground="#FFC99599"
                       TextWrapping="Wrap"  
                       VerticalAlignment="Bottom" 
                       HorizontalAlignment="Left" 
                       MinHeight="40"
                       MinWidth="360"/>
            <Grid x:Name="Mait_tool_Bt_close"
                      Grid.Column="1"
                      Grid.Row="1"
                      HorizontalAlignment="Center"
                      Margin="300,0,0,0" Focusable="True">
                <Ellipse x:Name="Close_Tip" 
                          Grid.Column="1"
                          Grid.Row="1"
                          Cursor="Hand"
                          Width="15"
                          Margin="0,0,10,0"
                          Tag="Close" 
                          MouseLeftButtonDown="Close_B_Tip"
                          HorizontalAlignment="Right" 
                          Height="15" 
                          VerticalAlignment="Top">
                    <Ellipse.Fill>
                        <RadialGradientBrush>
                            <GradientStop Color="#FFB84646" Offset="1"/>
                        </RadialGradientBrush>
                    </Ellipse.Fill>
                </Ellipse>
                <Ellipse x:Name="Max_Tip" 
                           Grid.Column="1"
                           Grid.Row="1"
                           Cursor="Hand"
                           Height="15" 
                           Width="15"
                           Margin="0,0,30,55"
                           Tag="Maximize" 
                           HorizontalAlignment="Right" 
                           VerticalAlignment="Bottom" MouseLeftButtonDown="MaxBot"
                           >
                    <Ellipse.Fill>
                        <RadialGradientBrush>
                            <GradientStop Color="#FFFFF33D" Offset="1"/>
                        </RadialGradientBrush>
                    </Ellipse.Fill>
                </Ellipse>
                <Ellipse x:Name="Mini_Tip" 
                        Grid.Column="1"
                        Grid.Row="1"
                        Cursor="Hand"
                        Height="15" 
                        Width="15"
                        Margin="0,0,50,0"
                        Tag="Minimize" 
                        HorizontalAlignment="Right" 
                        VerticalAlignment="Top"
                        MouseLeftButtonDown="Mini_Eve">
                    <Ellipse.Fill>
                        <RadialGradientBrush>

                            <GradientStop Color="#FF62C369" Offset="1"/>
                        </RadialGradientBrush>
                    </Ellipse.Fill>
                </Ellipse>
            </Grid>
            <TextBlock x:Name="Logo_win"               
                                 Margin="22,0,0,349" 
                                 Grid.Column="0"
                                 Grid.Row="1"
                                 MinHeight="70"
                                 MinWidth="100" Grid.RowSpan="2"><InlineUIContainer>                             
                          <Image x:Name="Logo_m"
                             Margin="15,12,0,16" 
                             Source="M:\Work\Coding\C# Projects\MTools\Icon\MTools Main.png"
                             Cursor="Hand" 
                             MouseLeftButtonDown="Git_About"
                             HorizontalAlignment="Left" 
                             Width="60" 
                              Grid.Row="1"
                             Grid.Column="0">
                          <Image.OpacityMask>
                              <ImageBrush>
                                  <ImageBrush.ImageSource>M:\Work\Coding\C# Projects\MTools\Icon\MTools Main.png</ImageBrush.ImageSource>
                              </ImageBrush>
                          </Image.OpacityMask>
                      </Image>        
            </InlineUIContainer><Run Text=" "/><InlineUIContainer>        
                      <TextBox Text="MTools"
                                Background="Transparent"
                                Foreground="White"
                                FontWeight="Bold"
                                FontSize="20"
                                Margin="-10,0,0,15"
                               BorderThickness="0" AllowDrop="False" Focusable="False"/>
            </InlineUIContainer></TextBlock>
            <Border x:Name="Stack_Btt"
                        Grid.Column="0" 
                        Grid.Row="2" Grid.RowSpan="1"
                        MaxWidth="220"
                        Width="220"
                        MinHeight="350">
                <StackPanel
                        Grid.Row="2"
                        Background="#FF211F2D"
                        ScrollViewer.VerticalScrollBarVisibility="Disabled" 
                        MinHeight="350" 
                        Width="220">
                    <Button Style="{StaticResource botSide}"
                            Tag="Craete Levels"
                            TextBlock.TextAlignment="Center"
                            x:Name="CreateF_Tools"
                            Content="Craete Levels"
                            Click="Click_Creat_But"/>
                </StackPanel>
            </Border>
            <Border x:Name="Bottom_Panel"
                        Grid.Row="3"
                        ClipToBounds="True" 
                        CornerRadius="0,0,10,10"
                        BorderThickness="0,1,0,0"
                        BorderBrush="#FFA1A1A1"
                        VerticalAlignment="Center"
                        MinHeight="20"
                        MaxHeight="20"
                        Width="220">
                <Grid
                        VerticalAlignment="Center" 
                        MinHeight="20"
                        MaxHeight="20"
                        HorizontalAlignment="Stretch" 
                        Width="600">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                    </Grid.ColumnDefinitions>
                    <TextBox x:Name="SycfilesT"
                                 Grid.Column="3"
                                 HorizontalAlignment="Stretch"
                                 FontSize="8"
                                 Foreground="#FFA1A1A1"
                                 VerticalAlignment="Stretch"
                                 Margin="0,2.5,10,2.5"
                                 BorderThickness="1,0,0,0"
                                 Background="Transparent"
                                 Text="File Path" 
                                 TextAlignment="Left"
                                 MinHeight="10" IsEnabled="False" TextWrapping="WrapWithOverflow" AllowDrop="False" Focusable="False"/>
                </Grid>
            </Border>
            <Border x:Name="pagesViews"
                        Grid.Column="1"
                        MinHeight="350"
                    Width="380"
                    Padding="5"
                        Grid.Row="2" Grid.RowSpan="1">
                <Grid x:Name="PagesViews"
                          HorizontalAlignment="Stretch"
                          VerticalAlignment="Stretch"
                          MinHeight="350"
                          Margin="0">
                    <Grid x:Name="MainGridCF"
                      HorizontalAlignment="Stretch"
                      VerticalAlignment="Stretch"
                      MinHeight="350"
                      Visibility="Visible">
                        <TabControl
                              x:Name="TabCOfCraeting"
                              Background="{x:Null}"
                              Foreground="White"
                              BorderBrush="{x:Null}" 
                              ScrollViewer.VerticalScrollBarVisibility="Disabled"  
                              VerticalContentAlignment="Stretch" 
                              HorizontalContentAlignment="Stretch" 
                              Padding="0,0,0,0" BorderThickness="0,0,0,0"
                              Margin="0"
                              MinHeight="350"
                              ClipToBounds="True" IsSynchronizedWithCurrentItem="False">
                            <TabItem
                                        x:Name="Levelss"
                                        TabIndex="0"
                                        Header="Footing"
                                        Width="100"
                                        BorderThickness="0,0,0,0"
                                        BorderBrush="{x:Null}"
                                        Margin="0,0,0,0" 
                                        TextBlock.FontSize="12"
                                        TextBlock.Foreground="#FF211F2D"
                                        TextBlock.TextAlignment="Center"
                                        FontWeight="Bold"
                                        Background="#FF211F2D" 
                                        Foreground="White"
                                        FontSize="12" Cursor="Hand" Loaded="Tab1Loaded" >
                                <Border BorderThickness="0,2,0,0"
                                        BorderBrush="White" Margin="0,0,0,0"
                                        Width="360"
                                        >

                                    <Grid  x:Name="FootingGrid" 
                                           Background="#FF19181C" 
                                           Width="360"
                                           ScrollViewer.VerticalScrollBarVisibility="Disabled"
                                           AutomationProperties.IsColumnHeader="True" 
                                           HorizontalAlignment="Stretch">
                                        <Grid.RowDefinitions>
                                            <RowDefinition 
                                                MinHeight="50"
                                                MaxHeight="45"/>
                                            <RowDefinition Height="1*"
                                                MinHeight="160"/>
                                            <RowDefinition 
                                                MinHeight="45"
                                                MaxHeight="45"/>
                                        </Grid.RowDefinitions>
                                        <Grid x:Name="SheetNamesBox"
                                          Grid.Row="0"
                                          Width="360"
                                          HorizontalAlignment="Center"
                                          >
                                            <Button x:Name="openEX" Height="30"
                                                             Width="25"
                                                             Margin="325,0,0,10"
                                                             HorizontalAlignment="Left"
                                                             VerticalAlignment="Bottom" Click="openEX_Click"/>
                                            <ComboBox x:Name="SheetsCombo"
                                                      Height="30"
                                                      Width="205"
                                                      VerticalAlignment="Center"
                                                      HorizontalAlignment="Right"
                                                      Margin="0,0,40,0" 
                                                      HorizontalContentAlignment="Center"
                                                      SelectionChanged="SheetsCombo_SelectionChanged"/>
                                            <TextBlock 
                                                     FontSize="12"
                                                     HorizontalAlignment="Left"
                                                     VerticalAlignment="Center"
                                                     Foreground="#FFE2DCDC"
                                                     FontWeight="Bold" 
                                                     Grid.Column="0" Margin="10,0,195,0" 
                                                     Height="20"><Run Text="Sheets' Names"/></TextBlock>
                                        </Grid>
                                        <Button Grid.Column="0" 
                                               Grid.Row="2"
                                               Height="25"
                                               Width="150"
                                               Margin="10,10,0,10"
                                               HorizontalAlignment="Left"
                                               Content="Create Levels"
                                               FontSize="12"
                                               FontWeight="Bold"
                                               Click="ImpFile_but"
                                               x:Name="bt_Impfile"/>
                                        <WindowsFormsHost Grid.Column="0" 
                                           Margin="10,50,10,0"
                                           MinHeight="200"
                                           x:Name="DataWinExcel" 
                                           ScrollViewer.VerticalScrollBarVisibility="Auto" 
                                           ClipToBounds="True" 
                                           IsManipulationEnabled="True" 
                                           OverridesDefaultStyle="True" 
                                           AllowDrop="True" AutomationProperties.IsRequiredForForm="True" AutomationProperties.IsColumnHeader="True" Grid.RowSpan="2">
                                            <Forms1:Spreadsheet x:Name="ExcelSheets" 
                                                     SheetTabControlWidth="330"
                                                     ActiveSheetIndex="0" 
                                                     IsAccessible="True"
                                                     BackColor="lightgray"
                                                     BorderStyle="Fixed3D"
                                                     EnableAutoCalculate="True"
                                                     BackgroundImageLayout="Tile"
                                                     Font="Segoe UI"
                                                     ForeColor="White"
                                                     SheetsBarVisible="False"
                                                     SheetTabVisible="False"
                                                     SheetView="Normal" 
                                                     RowHeaderVisible="True" 
                                                     ColumnHeaderVisible="True" 
                                                     AccessibleRole="Default" 
                                                     ImeMode="Off" EnableUndo="True"
                                                     >
                                                <Forms1:Spreadsheet.SheetTabContextMenuStrip>
                                                    <Forms:ContextMenuStrip/>
                                                </Forms1:Spreadsheet.SheetTabContextMenuStrip>
                                                <Forms1:Spreadsheet.ColumnHeaderContextMenuStrip>
                                                    <Forms:ContextMenuStrip/>
                                                </Forms1:Spreadsheet.ColumnHeaderContextMenuStrip>
                                                <Forms1:Spreadsheet.ContextMenuStrip>
                                                    <Forms:ContextMenuStrip/>
                                                </Forms1:Spreadsheet.ContextMenuStrip>
                                            </Forms1:Spreadsheet>
                                        </WindowsFormsHost>
                                    </Grid>
                                </Border>
                            </TabItem>
                        </TabControl>
                    </Grid>
                    <Grid x:Name="MainGridSC"
                      Visibility="Hidden">
                        <TabControl 
                        TabStripPlacement="Top"
                        Grid.Column="1"
                        Panel.ZIndex="1"
                        Background="#FF19181C"
                        Foreground="#FFE2DCDC"
                        BorderThickness="0,2,0,0"
                        Grid.RowSpan="1" 
                        BorderBrush="#FFA1A1A1" 
                           ScrollViewer.VerticalScrollBarVisibility="Disabled" VerticalContentAlignment="Stretch" 
                            HorizontalContentAlignment="Stretch" >
                        </TabControl>
                    </Grid>
                </Grid>
            </Border>
        </Grid>
    </Border>
</Window>
